#############################################################################
# Makefile for building: MetalPBR2
# Generated by qmake (3.1) (Qt 5.10.1)
# Project:  MetalPBR.pro
# Template: app
# Command: /usr/bin/qmake-qt5 -o Makefile MetalPBR.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT5BUILD -DQT5BUILD -DNGL_DEBUG -DQT_QML_DEBUG -DQT_OPENGL_LIB -DQT_QUICKWIDGETS_LIB -DQT_WIDGETS_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -march=native -march=native -g -std=gnu++1y -Wall -W -Wno-unused-parameter -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Iinclude -I/home/raluca/NGL/include -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtOpenGL -isystem /usr/include/qt5/QtQuickWidgets -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtQuick -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtQml -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtCore -Imoc -isystem /usr/include/libdrm -I/usr/lib64/qt5/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake-qt5
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake-qt5 -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake-qt5 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = MetalPBR21.0.0
DISTDIR = /home/raluca/Documents/cpp/rendering/MetalPBR/obj/MetalPBR21.0.0
LINK          = g++
LFLAGS        = -Wl,-z,origin -Wl,-rpath,\$$ORIGIN/L/home/raluca/NGL/lib -Wl,-rpath,/home/raluca/NGL/lib
LIBS          = $(SUBLIBS) -L/usr/local/lib -L/home/raluca/NGL/lib -l NGL -lQt5OpenGL -lQt5QuickWidgets -lQt5Widgets -lQt5Quick -lQt5Gui -lQt5Qml -lQt5Network -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/NGLScene.cpp \
		src/NGLSceneMouseControls.cpp \
		src/main.cpp moc/moc_NGLScene.cpp
OBJECTS       = obj/NGLScene.o \
		obj/NGLSceneMouseControls.o \
		obj/main.o \
		obj/moc_NGLScene.o
DIST          = .qmake.stash \
		MetalPBR.pro include/NGLScene.h \
		include/WindowParams.h src/NGLScene.cpp \
		src/NGLSceneMouseControls.cpp \
		src/main.cpp
QMAKE_TARGET  = MetalPBR2
DESTDIR       = 
TARGET        = MetalPBR2


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: MetalPBR.pro .qmake.cache /usr/lib64/qt5/mkspecs/linux-g++/qmake.conf /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		.qmake.cache \
		.qmake.stash \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/toolchain.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/home/raluca/NGL/UseNGL.pri \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/qt.prf \
		/usr/lib64/qt5/mkspecs/features/resources.prf \
		/usr/lib64/qt5/mkspecs/features/moc.prf \
		/usr/lib64/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt5/mkspecs/features/uic.prf \
		/usr/lib64/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib64/qt5/mkspecs/features/file_copies.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		MetalPBR.pro \
		/usr/lib64/libQt5OpenGL.prl \
		/usr/lib64/libQt5QuickWidgets.prl \
		/usr/lib64/libQt5Widgets.prl \
		/usr/lib64/libQt5Quick.prl \
		/usr/lib64/libQt5Gui.prl \
		/usr/lib64/libQt5Qml.prl \
		/usr/lib64/libQt5Network.prl \
		/usr/lib64/libQt5Core.prl
	$(QMAKE) -o Makefile MetalPBR.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
/usr/lib64/qt5/mkspecs/features/spec_pre.prf:
/usr/lib64/qt5/mkspecs/common/unix.conf:
/usr/lib64/qt5/mkspecs/common/linux.conf:
/usr/lib64/qt5/mkspecs/common/sanitize.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt5/mkspecs/common/g++-base.conf:
/usr/lib64/qt5/mkspecs/common/g++-unix.conf:
/usr/lib64/qt5/mkspecs/qconfig.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib64/qt5/mkspecs/features/qt_functions.prf:
/usr/lib64/qt5/mkspecs/features/qt_config.prf:
/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib64/qt5/mkspecs/features/spec_post.prf:
.qmake.cache:
.qmake.stash:
/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt5/mkspecs/features/toolchain.prf:
/usr/lib64/qt5/mkspecs/features/default_pre.prf:
/home/raluca/NGL/UseNGL.pri:
/usr/lib64/qt5/mkspecs/features/resolve_config.prf:
/usr/lib64/qt5/mkspecs/features/default_post.prf:
/usr/lib64/qt5/mkspecs/features/qml_debug.prf:
/usr/lib64/qt5/mkspecs/features/warn_on.prf:
/usr/lib64/qt5/mkspecs/features/qt.prf:
/usr/lib64/qt5/mkspecs/features/resources.prf:
/usr/lib64/qt5/mkspecs/features/moc.prf:
/usr/lib64/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib64/qt5/mkspecs/features/uic.prf:
/usr/lib64/qt5/mkspecs/features/unix/thread.prf:
/usr/lib64/qt5/mkspecs/features/qmake_use.prf:
/usr/lib64/qt5/mkspecs/features/file_copies.prf:
/usr/lib64/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib64/qt5/mkspecs/features/exceptions.prf:
/usr/lib64/qt5/mkspecs/features/yacc.prf:
/usr/lib64/qt5/mkspecs/features/lex.prf:
MetalPBR.pro:
/usr/lib64/libQt5OpenGL.prl:
/usr/lib64/libQt5QuickWidgets.prl:
/usr/lib64/libQt5Widgets.prl:
/usr/lib64/libQt5Quick.prl:
/usr/lib64/libQt5Gui.prl:
/usr/lib64/libQt5Qml.prl:
/usr/lib64/libQt5Network.prl:
/usr/lib64/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile MetalPBR.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib64/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents include/NGLScene.h include/WindowParams.h $(DISTDIR)/
	$(COPY_FILE) --parents src/NGLScene.cpp src/NGLSceneMouseControls.cpp src/main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc/moc_predefs.h
moc/moc_predefs.h: /usr/lib64/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -march=native -march=native -g -std=gnu++1y -Wall -W -Wno-unused-parameter -dM -E -o moc/moc_predefs.h /usr/lib64/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc/moc_NGLScene.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_NGLScene.cpp
moc/moc_NGLScene.cpp: include/WindowParams.h \
		/home/raluca/NGL/include/ngl/Camera.h \
		/home/raluca/NGL/include/ngl/Types.h \
		/home/raluca/NGL/include/ngl/glew.h \
		/home/raluca/NGL/include/ngl/Vec4.h \
		/home/raluca/NGL/include/ngl/Vec2.h \
		/home/raluca/NGL/include/ngl/Vec3.h \
		/home/raluca/NGL/include/ngl/Mat4.h \
		/home/raluca/NGL/include/ngl/RibExport.h \
		/home/raluca/NGL/include/ngl/Plane.h \
		/home/raluca/NGL/include/ngl/AABB.h \
		/home/raluca/NGL/include/ngl/BBox.h \
		/home/raluca/NGL/include/ngl/AbstractVAO.h \
		/home/raluca/NGL/include/ngl/Text.h \
		/home/raluca/NGL/include/ngl/Colour.h \
		/home/raluca/NGL/include/ngl/VAOFactory.h \
		/home/raluca/NGL/include/ngl/SimpleVAO.h \
		/home/raluca/NGL/include/ngl/Transformation.h \
		/home/raluca/NGL/include/ngl/NGLassert.h \
		/home/raluca/NGL/include/ngl/Obj.h \
		/home/raluca/NGL/include/ngl/Texture.h \
		/home/raluca/NGL/include/ngl/Image.h \
		/home/raluca/NGL/include/ngl/AbstractMesh.h \
		include/CubeMap.h \
		include/NGLScene.h \
		moc/moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include moc/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/raluca/Documents/cpp/rendering/MetalPBR -I/home/raluca/Documents/cpp/rendering/MetalPBR/include -I/home/raluca/NGL/include -I/usr/include/qt5 -I/usr/include/qt5/QtOpenGL -I/usr/include/qt5/QtQuickWidgets -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/c++/8/x86_64-redhat-linux -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-redhat-linux/8/include -I/usr/local/include -I/usr/include include/NGLScene.h -o moc/moc_NGLScene.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

obj/NGLScene.o: src/NGLScene.cpp include/NGLScene.h \
		include/WindowParams.h \
		/home/raluca/NGL/include/ngl/Camera.h \
		/home/raluca/NGL/include/ngl/Types.h \
		/home/raluca/NGL/include/ngl/glew.h \
		/home/raluca/NGL/include/ngl/Vec4.h \
		/home/raluca/NGL/include/ngl/Vec2.h \
		/home/raluca/NGL/include/ngl/Vec3.h \
		/home/raluca/NGL/include/ngl/Mat4.h \
		/home/raluca/NGL/include/ngl/RibExport.h \
		/home/raluca/NGL/include/ngl/Plane.h \
		/home/raluca/NGL/include/ngl/AABB.h \
		/home/raluca/NGL/include/ngl/BBox.h \
		/home/raluca/NGL/include/ngl/AbstractVAO.h \
		/home/raluca/NGL/include/ngl/Text.h \
		/home/raluca/NGL/include/ngl/Colour.h \
		/home/raluca/NGL/include/ngl/VAOFactory.h \
		/home/raluca/NGL/include/ngl/SimpleVAO.h \
		/home/raluca/NGL/include/ngl/Transformation.h \
		/home/raluca/NGL/include/ngl/NGLassert.h \
		/home/raluca/NGL/include/ngl/Obj.h \
		/home/raluca/NGL/include/ngl/Texture.h \
		/home/raluca/NGL/include/ngl/Image.h \
		/home/raluca/NGL/include/ngl/AbstractMesh.h \
		include/CubeMap.h \
		/home/raluca/NGL/include/ngl/NGLInit.h \
		/home/raluca/NGL/include/ngl/Singleton.h \
		/home/raluca/NGL/include/ngl/VAOPrimitives.h \
		/home/raluca/NGL/include/ngl/NGLStream.h \
		/home/raluca/NGL/include/ngl/Random.h \
		/home/raluca/NGL/include/ngl/ShaderLib.h \
		/home/raluca/NGL/include/ngl/Shader.h \
		/home/raluca/NGL/include/ngl/ShaderProgram.h \
		/home/raluca/NGL/include/ngl/Util.h \
		/home/raluca/NGL/include/ngl/Mat3.h \
		/home/raluca/NGL/include/ngl/SimpleIndexVAO.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/NGLScene.o src/NGLScene.cpp

obj/NGLSceneMouseControls.o: src/NGLSceneMouseControls.cpp include/NGLScene.h \
		include/WindowParams.h \
		/home/raluca/NGL/include/ngl/Camera.h \
		/home/raluca/NGL/include/ngl/Types.h \
		/home/raluca/NGL/include/ngl/glew.h \
		/home/raluca/NGL/include/ngl/Vec4.h \
		/home/raluca/NGL/include/ngl/Vec2.h \
		/home/raluca/NGL/include/ngl/Vec3.h \
		/home/raluca/NGL/include/ngl/Mat4.h \
		/home/raluca/NGL/include/ngl/RibExport.h \
		/home/raluca/NGL/include/ngl/Plane.h \
		/home/raluca/NGL/include/ngl/AABB.h \
		/home/raluca/NGL/include/ngl/BBox.h \
		/home/raluca/NGL/include/ngl/AbstractVAO.h \
		/home/raluca/NGL/include/ngl/Text.h \
		/home/raluca/NGL/include/ngl/Colour.h \
		/home/raluca/NGL/include/ngl/VAOFactory.h \
		/home/raluca/NGL/include/ngl/SimpleVAO.h \
		/home/raluca/NGL/include/ngl/Transformation.h \
		/home/raluca/NGL/include/ngl/NGLassert.h \
		/home/raluca/NGL/include/ngl/Obj.h \
		/home/raluca/NGL/include/ngl/Texture.h \
		/home/raluca/NGL/include/ngl/Image.h \
		/home/raluca/NGL/include/ngl/AbstractMesh.h \
		include/CubeMap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/NGLSceneMouseControls.o src/NGLSceneMouseControls.cpp

obj/main.o: src/main.cpp include/NGLScene.h \
		include/WindowParams.h \
		/home/raluca/NGL/include/ngl/Camera.h \
		/home/raluca/NGL/include/ngl/Types.h \
		/home/raluca/NGL/include/ngl/glew.h \
		/home/raluca/NGL/include/ngl/Vec4.h \
		/home/raluca/NGL/include/ngl/Vec2.h \
		/home/raluca/NGL/include/ngl/Vec3.h \
		/home/raluca/NGL/include/ngl/Mat4.h \
		/home/raluca/NGL/include/ngl/RibExport.h \
		/home/raluca/NGL/include/ngl/Plane.h \
		/home/raluca/NGL/include/ngl/AABB.h \
		/home/raluca/NGL/include/ngl/BBox.h \
		/home/raluca/NGL/include/ngl/AbstractVAO.h \
		/home/raluca/NGL/include/ngl/Text.h \
		/home/raluca/NGL/include/ngl/Colour.h \
		/home/raluca/NGL/include/ngl/VAOFactory.h \
		/home/raluca/NGL/include/ngl/SimpleVAO.h \
		/home/raluca/NGL/include/ngl/Transformation.h \
		/home/raluca/NGL/include/ngl/NGLassert.h \
		/home/raluca/NGL/include/ngl/Obj.h \
		/home/raluca/NGL/include/ngl/Texture.h \
		/home/raluca/NGL/include/ngl/Image.h \
		/home/raluca/NGL/include/ngl/AbstractMesh.h \
		include/CubeMap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/moc_NGLScene.o: moc/moc_NGLScene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_NGLScene.o moc/moc_NGLScene.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

